#!/usr/bin/with-contenv sh

uwsgi --chdir=/hb \
  --module=html_browser.wsgi:application \
  --master \
  --socket=0.0.0.0:8000 \
  --pidfile=/tmp/project-master.pid \
  --vacuum \
  --uid=$USERID --gid=$GROUPID \
  --buffer-size=32768 \
  --max-requests=5000 \
  --processes=5 \
  --umask=002
