dist: xenial
services:
  - docker

sudo: required

install: 
  - docker build -t html_browser --pull .
  - sudo mkdir /config
  - sudo mkdir -p /config/logs/hb
  - sudo chown -R $USER /config
  - sudo apt-get update
  - sudo apt-get install -y coreutils
  - TRAVIS_UID=$(id -u)
  - TRAVIS_GID=$(id -g)
  - docker run -d -p 8000:80 -v /config:/config -v /:/data1 -e USERID=$TRAVIS_UID -e GROUPID=$TRAVIS_GID -e USERNAME=hb_user -e GROUPNAME=hb_group -e HOMEDIR=/hb --name html_browser html_browser
  - docker ps -a

script: 
  - docker exec -it html_browser /bin/bash -c "cd /hb; python manage.py test"

