ARG version
from bfincher/html_browser:alpine-sqlite_${version}

env PYTHONBUFFERED 1

workdir /hb

run apk add --no-cache mariadb-client mariadb-connector-c && \
    apk add --no-cache --virtual .builddeps mariadb-dev gcc musl-dev python3-dev && \
    pip install --no-cache mysqlclient==2.1.1 && \
    apk del .builddeps && \
    find /usr/local \
        \( -type d -a -name test -o -name tests \) \
        -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
        -exec rm -rf '{}' + && \
    cp /hb/docker_mysql.env /hb/.env && \
    cp /init_mysql_db.sh /init_db.sh

ENV DB_USER="db_user"
ENV DB_PASS="db_pass"
ENV DB_ROOT_PASS="db_root_pass"
env DB_NAME="hb_db"
env DB_HOST="db"
