version: "3.3"

services:
    db:
        image: mariadb:10.6
        hostname: ${DB_HOST}
        volumes:
            - /Volumes/docker_configs/html_browser/db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
        networks:
            - backend
        restart: unless-stopped

    nginx:
        build:
          context: .
          dockerfile: nginx_Dockerfile
        hostname: htmlbrowser
        ports: 
            - 8000:80
        volumes:
            - nginx_dynamic_config:/etc/nginx/conf.d/
            - hbmedia:/hbmedia
            - /Volumes/data1:/data1
        depends_on:
            - django
        networks:
            backend:
            frontend:
               ipv4_address: 172.18.0.105
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST_HTTPS=www.fincherhome.com

    django:
        image: bfincher/html_browser:alpine-mysql_${VERSION}
        hostname: htmlbrowser_django
        volumes:
            - /Volumes/docker_configs/html_browser/config:/config
            - /Volumes/Pictures:/Pictures
            - /Volumes/Videos:/Videos
            - hbmedia:/hb/media
            - nginx_dynamic_config:/nginx_config
        environment:
            - USERID=1012
            - GROUPID=1012
            - USERNAME=hb
            - GROUPNAME=hb
            - HOMEDIR=/hb 
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_ROOT_PASS=${DB_ROOT_PASS}
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
        depends_on:
            - db
        networks:
            - backend
        restart: unless-stopped

volumes:
    hbmedia:
    nginx_dynamic_config:

networks:
    frontend:
        external: true
    backend:
