from bfincher/html_browser:alpine-sqlite

env PYTHONBUFFERED 1

workdir /hb

run apk add --no-cache mariadb-client mariadb-connector-c && \
    apk add --no-cache --virtual .builddeps mariadb-dev gcc musl-dev python3-dev && \
    pip install --no-cache mysqlclient==1.4.2 && \
    apk del .builddeps && \
    find /usr/local \
        \( -type d -a -name test -o -name tests \) \
        -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
        -exec rm -rf '{}' + && \
    runDeps="$( \
        scanelf --needed --nobanner --recursive /usr/local \
                | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
                | sort -u \
                | xargs -r apk info --installed \
                | sort -u \
    )" && \
    apk add --virtual .rundeps $runDeps && \
    cp /hb/html_browser/docker_mysql.env /.env && \
    cp /empty.sh /init_db.sh

ENV DB_USER="db_user"
ENV DB_PASS="db_pass"
ENV DB_ROOT_PASS="db_root_pass"
env DB_NAME="hb_db"
env DB_HOST="mysql"
