#!/usr/bin/with-contenv sh

cd /hb
sleep 10
gunicorn html_browser.wsgi:application --user ${USERNAME} \
--access-logfile /var/log/gunicorn-access.log \
--error-logfile /var/log/gunicorn-error.log \
--worker-tmp-dir /dev/shm \
--bind 0.0.0.0:8000 \
--workers 2 \
--threads 2 \
--worker-class=gthread
