#!/usr/bin/with-contenv sh
set -e

#while true; do date; sleep 1; done

cd /hb
APP_CONFIG_UIDGID="${USERID}:${GROUPID}"

if [ ! -d ${APP_CONFIG}/logs/hb ]; then
    su ${USERNAME} -c "mkdir -p ${APP_CONFIG}/logs/hb"
fi

if [ $(stat -c "%u:%g" ${APP_CONFIG}) != "${APP_CONFIG_UIDGID}" ]; then
    chown -R ${APP_CONFIG_UIDGID} "$APP_CONFIG"
fi

/init_db.sh

su ${USERNAME} -c "python3 manage.py migrate"
python3 manage.py create_superuser_with_password --user admin --password pass --noinput --email 'admin@example.com' --if-no-superuser
